# Generated by Django 4.2.30 on 2026-06-22 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_celerytask'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='login_status',
            field=models.CharField(choices=[('NOT_ATTEMPTED', 'Not Attempted'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='NOT_ATTEMPTED', max_length=20),
        ),
    ]
