# Generated by Django 4.2.30 on 2026-06-22 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_application_login_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestValidation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relevance_score', models.FloatField(default=0)),
                ('elements_found', models.IntegerField(default=0)),
                ('elements_total', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('HIGHLY_RELEVANT', 'Highly Relevant (90-100%)'), ('RELEVANT', 'Relevant (70-89%)'), ('SOMEWHAT_RELEVANT', 'Somewhat Relevant (50-69%)'), ('IRRELEVANT', 'Irrelevant (<50%)')], default='IRRELEVANT', max_length=20)),
                ('validation_details', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='test_validations', to='core.application')),
                ('test_case', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quality_validation', to='core.testcase')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QualityMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coverage_score', models.FloatField(default=0)),
                ('reliability_score', models.FloatField(default=0)),
                ('accuracy_score', models.FloatField(default=0)),
                ('relevance_score', models.FloatField(default=0)),
                ('overall_score', models.FloatField(default=0)),
                ('grade', models.CharField(choices=[('A', 'Excellent (90-100)'), ('B', 'Good (80-89)'), ('C', 'Fair (70-79)'), ('D', 'Poor (60-69)'), ('F', 'Failing (<60)')], default='F', max_length=1)),
                ('recommendations', models.JSONField(default=list)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('application', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quality_metrics', to='core.application')),
            ],
        ),
        migrations.CreateModel(
            name='FlakinessReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('runs_executed', models.IntegerField(default=5)),
                ('runs_passed', models.IntegerField(default=0)),
                ('runs_failed', models.IntegerField(default=0)),
                ('flakiness_percentage', models.FloatField(default=0)),
                ('status', models.CharField(choices=[('STABLE', 'Stable (0-10% failure)'), ('MOSTLY_STABLE', 'Mostly Stable (10-20% failure)'), ('FLAKY', 'Flaky (20-50% failure)'), ('VERY_FLAKY', 'Very Flaky (>50% failure)')], default='VERY_FLAKY', max_length=20)),
                ('failure_patterns', models.JSONField(default=dict)),
                ('failure_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_run', models.DateTimeField(blank=True, null=True)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flakiness_reports', to='core.application')),
                ('test_case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flakiness_reports', to='core.testcase')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CoverageReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_coverage', models.FloatField(default=0)),
                ('form_coverage', models.FloatField(default=0)),
                ('workflow_coverage', models.FloatField(default=0)),
                ('overall_coverage', models.FloatField(default=0)),
                ('total_pages', models.IntegerField(default=0)),
                ('tested_pages', models.IntegerField(default=0)),
                ('total_forms', models.IntegerField(default=0)),
                ('tested_forms', models.IntegerField(default=0)),
                ('total_workflows', models.IntegerField(default=0)),
                ('tested_workflows', models.IntegerField(default=0)),
                ('untested_elements', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coverage_reports', to='core.application')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BugValidation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confidence_score', models.FloatField(default=0)),
                ('is_verified', models.BooleanField(default=False)),
                ('verification_status', models.CharField(choices=[('VERIFIED', 'Real Bug'), ('FALSE_POSITIVE', 'False Positive'), ('NEEDS_REVIEW', 'Needs Manual Review')], default='NEEDS_REVIEW', max_length=20)),
                ('reproducibility_count', models.IntegerField(default=1)),
                ('reproducibility_score', models.FloatField(default=0)),
                ('severity_score', models.FloatField(default=0)),
                ('error_type', models.CharField(blank=True, max_length=50)),
                ('validation_methods', models.JSONField(default=dict)),
                ('validation_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bug_validations', to='core.application')),
                ('bug', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='validation', to='core.bug')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
