# Generated by Django 4.2.30 on 2026-06-23 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_testvalidation_qualitymetrics_flakinessreport_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='storage_state',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testcase',
            name='validation_status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('VERIFIED', 'Verified'), ('BROKEN', 'Broken')], default='DRAFT', max_length=20),
        ),
        migrations.CreateModel(
            name='APIEndpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(max_length=10)),
                ('url_pattern', models.CharField(max_length=1000)),
                ('request_schema', models.JSONField(blank=True, default=dict)),
                ('response_schema', models.JSONField(blank=True, default=dict)),
                ('auth_type', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_endpoints', to='core.application')),
            ],
            options={
                'ordering': ['url_pattern'],
                'unique_together': {('application', 'method', 'url_pattern')},
            },
        ),
        migrations.AddField(
            model_name='bug',
            name='api_endpoint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bugs', to='core.apiendpoint'),
        ),
    ]
