# Generated by Django 4.2.30 on 2026-06-23 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_application_storage_state_testcase_validation_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='login_error',
            field=models.TextField(blank=True, null=True),
        ),
    ]
