# Generated by Django 4.2.30 on 2026-06-28 06:07

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_application_login_error'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='qualitymetrics',
            options={'ordering': ['-last_updated']},
        ),
        migrations.AddField(
            model_name='application',
            name='industry',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='testcase',
            name='generation_context',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='password',
            field=core.models.EncryptedCharField(blank=True, null=True),
        ),
    ]
