# Generated by Django 4.2.30 on 2026-06-28 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_qualitymetrics_options_application_industry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bug',
            name='bug_type',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='bug',
            name='element_selector',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='bug',
            name='screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='bugs/'),
        ),
        migrations.AddField(
            model_name='bug',
            name='status',
            field=models.CharField(default='open', max_length=32),
        ),
        migrations.AddField(
            model_name='bug',
            name='steps_to_reproduce',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='elements',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='page_type',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='workflows',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='bug',
            name='test_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bugs', to='core.testrun'),
        ),
        migrations.CreateModel(
            name='AgentSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(max_length=64)),
                ('status', models.CharField(max_length=32)),
                ('llm_model', models.CharField(max_length=128)),
                ('steps_taken', models.JSONField(default=list)),
                ('tokens_used', models.IntegerField(default=0)),
                ('duration_seconds', models.FloatField(null=True)),
                ('result_summary', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_sessions', to='core.application')),
            ],
        ),
    ]
