# Generated by Django 4.2.30 on 2026-06-28 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_bug_bug_type_bug_element_selector_bug_screenshot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bug',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bugs', to='core.application'),
        ),
    ]
