# Generated by Django 4.2.30 on 2026-07-05 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_bug_application'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('IDLE', 'Idle'), ('DISCOVERING', 'Discovering'), ('DISCOVERED', 'Discovered'), ('FAILED', 'Failed')], db_index=True, default='IDLE', max_length=20),
        ),
        migrations.AlterField(
            model_name='bug',
            name='severity',
            field=models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], db_index=True, default='medium', max_length=20),
        ),
        migrations.AlterField(
            model_name='celerytask',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('progress', 'In Progress'), ('success', 'Success'), ('failed', 'Failed')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='flakinessreport',
            name='status',
            field=models.CharField(choices=[('STABLE', 'Stable (0-10% failure)'), ('MOSTLY_STABLE', 'Mostly Stable (10-20% failure)'), ('FLAKY', 'Flaky (20-50% failure)'), ('VERY_FLAKY', 'Very Flaky (>50% failure)')], db_index=True, default='VERY_FLAKY', max_length=20),
        ),
        migrations.AlterField(
            model_name='testrun',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='testvalidation',
            name='status',
            field=models.CharField(choices=[('HIGHLY_RELEVANT', 'Highly Relevant (90-100%)'), ('RELEVANT', 'Relevant (70-89%)'), ('SOMEWHAT_RELEVANT', 'Somewhat Relevant (50-69%)'), ('IRRELEVANT', 'Irrelevant (<50%)')], db_index=True, default='IRRELEVANT', max_length=20),
        ),
    ]
