# Generated by Django 4.2.30 on 2026-07-06 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_application_status_alter_bug_severity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcase',
            name='category',
            field=models.CharField(default='Generic', max_length=32),
        ),
    ]
