# Generated by Django 4.2.30 on 2026-07-08 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_testcase_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='accessibility_roles',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
