# Generated by Django 4.2.30 on 2026-07-08 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_page_accessibility_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='connections',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
