# Generated by Django 4.2.30 on 2026-07-08 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_page_connections'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='semantic_metadata',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
