# Generated by Django 4.2.30 on 2026-07-09 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_page_semantic_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='ai_summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
