# Generated by Django 4.2.30 on 2026-07-12 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_page_ai_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='use_llm_in_crawl',
            field=models.BooleanField(default=False),
        ),
    ]
