# Generated by Django 5.2.16 on 2026-07-16 06:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_application_use_llm_in_crawl'),
    ]

    operations = [
        migrations.AddField(
            model_name='celerytask',
            name='app',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='celery_tasks', to='core.application'),
        ),
    ]
