# Generated by Django 4.2.30 on 2026-07-27 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_add_app_to_celerytask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='celerytask',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('progress', 'In Progress'), ('success', 'Success'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, max_length=20),
        ),
    ]
