# Generated by Django 4.2.30 on 2026-07-29 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_teammember'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcase',
            name='self_healed_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='testresult',
            name='auto_healed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='testresult',
            name='healing_details',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='testrun',
            name='self_healed_count',
            field=models.IntegerField(default=0),
        ),
    ]
