# Generated by Django 4.2.30 on 2026-08-04 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_agentsession_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebVitalsResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('lcp_ms', models.FloatField(default=0.0, help_text='Largest Contentful Paint in ms')),
                ('cls', models.FloatField(default=0.0, help_text='Cumulative Layout Shift')),
                ('ttfb_ms', models.FloatField(default=0.0, help_text='Time to First Byte in ms')),
                ('performance_score', models.IntegerField(default=0, help_text='Overall performance score 0-100')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='web_vitals_results', to='core.application')),
                ('page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='web_vitals_results', to='core.page')),
            ],
        ),
        migrations.CreateModel(
            name='QualityMetricsSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coverage_score', models.FloatField(default=0)),
                ('reliability_score', models.FloatField(default=0)),
                ('accuracy_score', models.FloatField(default=0)),
                ('relevance_score', models.FloatField(default=0)),
                ('overall_score', models.FloatField(default=0)),
                ('web_vitals_score', models.FloatField(default=0)),
                ('grade', models.CharField(choices=[('A', 'Excellent (90-100)'), ('B', 'Good (80-89)'), ('C', 'Fair (70-79)'), ('D', 'Poor (60-69)'), ('F', 'Failing (<60)')], default='F', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quality_snapshots', to='core.application')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PerformanceThreshold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_latency_warning_ms', models.IntegerField(default=500)),
                ('api_latency_critical_ms', models.IntegerField(default=2000)),
                ('page_load_warning_ms', models.IntegerField(default=3000)),
                ('page_load_critical_ms', models.IntegerField(default=8000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='performance_thresholds', to='core.application')),
            ],
        ),
        migrations.CreateModel(
            name='LoadTestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concurrency', models.IntegerField(default=20)),
                ('total_requests', models.IntegerField(default=0)),
                ('p50_ms', models.FloatField(default=0.0)),
                ('p95_ms', models.FloatField(default=0.0)),
                ('p99_ms', models.FloatField(default=0.0)),
                ('error_rate', models.FloatField(default=0.0)),
                ('requests_per_second', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('api_endpoint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='load_test_results', to='core.apiendpoint')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='load_test_results', to='core.application')),
            ],
        ),
    ]
