# Generated by Django 4.2.30 on 2026-08-11 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_sync_performance_schema'),
    ]

    operations = [
        migrations.CreateModel(
            name='APITestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('method', models.CharField(max_length=10)),
                ('url', models.CharField(max_length=1000)),
                ('headers', models.JSONField(blank=True, default=dict)),
                ('body', models.JSONField(blank=True, default=dict)),
                ('expected_status', models.IntegerField(default=200)),
                ('expected_body_contains', models.JSONField(blank=True, default=list)),
                ('auth_required', models.BooleanField(default=False)),
                ('ai_generated', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('api_endpoint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_test_cases', to='core.apiendpoint')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_test_cases', to='core.application')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VisualBaseline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.IntegerField(default=0)),
                ('screenshot_path', models.CharField(max_length=500)),
                ('width', models.IntegerField(default=1280)),
                ('height', models.IntegerField(default=800)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visual_baselines', to='core.page')),
            ],
            options={
                'ordering': ['-updated_at'],
                'unique_together': {('page', 'step_number')},
            },
        ),
        migrations.CreateModel(
            name='VisualDiff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.IntegerField(default=0)),
                ('diff_percentage', models.FloatField(default=0.0)),
                ('diff_screenshot_path', models.CharField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('PASSED', 'Passed'), ('FAILED', 'Failed'), ('NO_BASELINE', 'No Baseline')], default='NO_BASELINE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('baseline', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diffs', to='core.visualbaseline')),
                ('test_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visual_diffs', to='core.testrun')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='APITestRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=20)),
                ('actual_status_code', models.IntegerField(blank=True, null=True)),
                ('response_body', models.TextField(blank=True)),
                ('response_time_ms', models.FloatField(blank=True, null=True)),
                ('error', models.TextField(blank=True)),
                ('passed', models.BooleanField(default=False)),
                ('failure_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('api_test_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='core.apitestcase')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
