# Generated by Django 4.2.30 on 2026-08-16 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_apitestcase_visualbaseline_visualdiff_apitestrun'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcase',
            name='consecutive_flips',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='testcase',
            name='flakiness_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='testcase',
            name='is_flaky',
            field=models.BooleanField(default=False),
        ),
    ]
