# Generated by Django 4.2.30 on 2026-08-16 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_testcase_consecutive_flips_testcase_flakiness_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testrun',
            name='css_coverage_pct',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='testrun',
            name='execution_duration_ms',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='testrun',
            name='execution_mode',
            field=models.CharField(blank=True, default='HEADLESS', max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='testrun',
            name='js_coverage_pct',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
